### ISSUE TITLE
How are you licensing this?

### ISSUE THREAD

**Issue by emiddleton** [wagnerjfr/mysql-group-replication-docker-compose#2]
I was looking at adapting this to use for testing a driver but noticed you haven't included a license. Are you happy for your work to be used in this way and under what licensing conditions.  If you just put this out for anyone to use MIT or BSD licenses do that.

**Comment by wagnerjfr** [comment]
Hi @emiddleton, thanks for the interest in my repo.
I'll be adding the license GPLv3 which is the one that MySQL also has.
It'll appear in the repository soon.
