### ISSUE TITLE
Can't log in with password

### ISSUE THREAD

**Issue by king-sley-o** [wagnerjfr/mysql-group-replication-docker-compose#5]
The password supplied to the MYSQL_ROOT_PASSWORD is not logging me in to the container and no password is generated either from the log.  Tried it over and over again... getting error ````error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'````

**Comment by wagnerjfr** [comment]
What have your tried? Following the steps there we can connect to the MySQL inside the container and trigger some commands like:
```
for N in 1 2 3
do docker-compose exec node$N mysql -uroot -pmypass \
  -e "SHOW VARIABLES WHERE Variable_name = 'hostname';" \
  -e "SELECT * FROM performance_schema.replication_group_members;"
done
```
Correct?

**Comment by king-sley-o** [comment]
Working now...
