### ISSUE TITLE
Unable to add other members of the group

### ISSUE THREAD

**Issue by king-sley-o** [wagnerjfr/mysql-group-replication-docker-compose#6]
When i try  to add other members to the group
````
for N in 2 3
do docker-compose exec node$N mysql -uroot -p@mypass \
  -e "change master to master_user='myuser' for channel 'group_replication_recovery';" \
  -e "START GROUP_REPLICATION;"
done
````
I have this error
>  2022-06-10T07:32:28.350709Z 0 [ERROR] [MY-011526] [Repl] Plugin group_replication reported: 'This member has more executed transactions than those present in the group. Local transactions: 245ddc6d-e889-11ec-963b-0242ac150003:1-6 > Group transactions: 245d2c96-e889-11ec-b50a-0242ac150002:1-11, 7b3cde30-e713-11ec-8b14-0242ac150099:1-5'

How do i fix this?

**Comment by wagnerjfr** [comment]
Can you do all the steps of the README (in that sequence) with success?
